# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ironic', models.BooleanField(default=False, verbose_name='contem ironia')),
                ('review', models.IntegerField(choices=[(1, 'Positivo'), (0, 'Neutro'), (-1, 'Negativo')], verbose_name='Avaliacao')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.TextField(max_length=300, verbose_name='text')),
                ('tweet_username', models.CharField(max_length=200, verbose_name='username')),
                ('tweet_id', models.PositiveIntegerField(verbose_name='id do tweet')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.Tweet'),
        ),
    ]
