# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.BigIntegerField(verbose_name='id do tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_username',
            field=models.CharField(max_length=255, verbose_name='username'),
        ),
    ]
